#!/usr/bin/env bash
# live-e2e-verify.sh — Self-bootstrapping agentic workflow E2E verifier.
#
# Usage: bash tests/e2e/live-e2e-verify.sh [--dry-run]
#
# What it does:
#   1. Creates a specially-tagged test issue in this repo
#   2. Waits for the issue-ops workflow to run and post an agent comment
#   3. Validates the comment contains a valid issue-action-plan trace
#   4. Closes and locks the test issue
#   5. Exits 0 (pass) or 1 (fail) with a summary report
#
# Requirements:
#   - GH_TOKEN with issues:write + actions:read
#   - gh CLI installed
#   - jq installed
#
# Environment variables:
#   REPO          — owner/repo to test against (default: current repo from gh)
#   MAX_WAIT_SEC  — seconds to wait for agent response (default: 300)
#   DRY_RUN       — if 'true', skip issue creation and just validate
#   ISSUE_NUMBER  — if set, skip creation and verify this existing issue

set -euo pipefail

REPO="${REPO:-$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null || echo '')}"
MAX_WAIT_SEC="${MAX_WAIT_SEC:-300}"
POLL_INTERVAL=15
DRY_RUN="${DRY_RUN:-false}"
ISSUE_NUMBER="${ISSUE_NUMBER:-}"

# ANSI colours
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${NC}[$(date -u +%H:%M:%S)] $*"; }
ok()   { echo -e "${GREEN}✓ $*${NC}"; }
warn() { echo -e "${YELLOW}⚠ $*${NC}"; }
fail() { echo -e "${RED}✗ $*${NC}"; }

if [ -z "$REPO" ]; then
  fail "REPO is not set and could not be detected from gh CLI"
  exit 1
fi

# ── Parse args ────────────────────────────────────────────────────────────────

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --issue=*) ISSUE_NUMBER="${arg#*=}" ;;
  esac
done

# ── Create test issue ─────────────────────────────────────────────────────────

TEST_LABEL="openci:e2e-test"
RUN_ID="${GITHUB_RUN_ID:-local-$(date +%s)}"
ISSUE_TITLE="[openci-e2e] Automated self-test run ${RUN_ID}"
ISSUE_BODY="$(cat << 'EOF'
## OpenCI E2E Self-Test

This issue was automatically created by the OpenCI test suite to verify the
end-to-end agentic issue workflow.

**Expected behaviour:**
1. The `issue-ops` workflow triggers on this issue
2. Stage 1 (Ingest) normalises the payload
3. Stage 2 (Enrich) builds the agent workspace
4. Stage 3 (Agent Plan) returns an `issue-action-plan/v1` JSON
5. Stage 4 (Execute) posts an audit comment linking to the plan

**This issue will be automatically closed** once the E2E test validates the agent response.

> Auto-generated by `tests/e2e/live-e2e-verify.sh`
EOF
)"

if [ "$DRY_RUN" = "true" ]; then
  warn "DRY_RUN mode: skipping issue creation"
elif [ -z "$ISSUE_NUMBER" ]; then
  log "Creating E2E test issue in ${REPO}..."

  # Ensure the e2e test label exists
  gh label create "${TEST_LABEL}" --repo "${REPO}" \
    --description "OpenCI automated E2E test issue" \
    --color "0075ca" 2>/dev/null || true

  ISSUE_NUMBER=$(gh issue create \
    --repo "${REPO}" \
    --title "${ISSUE_TITLE}" \
    --body "${ISSUE_BODY}" \
    --label "${TEST_LABEL}" \
    --json number -q '.number')

  log "Created issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}"
fi

# ── Wait for agent response ────────────────────────────────────────────────────

log "Waiting for agent response on issue #${ISSUE_NUMBER} (max ${MAX_WAIT_SEC}s)..."

ELAPSED=0
AGENT_COMMENT=""

while [ "$ELAPSED" -lt "$MAX_WAIT_SEC" ]; do
  COMMENTS=$(gh issue view "${ISSUE_NUMBER}" \
    --repo "${REPO}" \
    --json comments \
    --jq '.comments[]' 2>/dev/null || echo "")

  # Look for openci-agent-run marker or issue-action-plan/v1 in any comment
  while IFS= read -r comment; do
    body=$(echo "$comment" | jq -r '.body // ""')
    if echo "$body" | grep -q 'openci-agent-run\|issue-action-plan/v1\|openci:audit'; then
      AGENT_COMMENT="$body"
      break 2
    fi
  done < <(echo "$COMMENTS" | jq -c '.')

  log "No agent comment yet (${ELAPSED}s elapsed)... retrying in ${POLL_INTERVAL}s"
  sleep "$POLL_INTERVAL"
  ELAPSED=$((ELAPSED + POLL_INTERVAL))
done

# ── Validate agent response ───────────────────────────────────────────────────

PASS=true
REPORT=""

if [ -z "$AGENT_COMMENT" ]; then
  fail "Agent did not post a response within ${MAX_WAIT_SEC}s"
  PASS=false
  REPORT="FAIL: No agent comment found after ${MAX_WAIT_SEC}s"
else
  ok "Agent posted a response comment"
  REPORT="Agent comment found."

  # Check for reasoning marker
  if echo "$AGENT_COMMENT" | grep -qi 'reasoning\|audit\|plan'; then
    ok "Agent comment contains reasoning/audit content"
  else
    warn "Agent comment may be missing reasoning block"
    REPORT="${REPORT}\nWARN: reasoning block not found in comment"
  fi

  # Check comment is not an error
  if echo "$AGENT_COMMENT" | grep -qi 'error\|failed\|exception' && \
     ! echo "$AGENT_COMMENT" | grep -qi 'issue-action-plan\|openci-agent-run'; then
    fail "Agent comment looks like an error output"
    PASS=false
    REPORT="${REPORT}\nFAIL: Comment appears to be an error, not a plan"
  fi

  # Check workflow run status
  log "Checking issue-ops workflow run status..."
  WORKFLOW_STATUS=$(gh run list \
    --repo "${REPO}" \
    --workflow "issue-ops.yml" \
    --limit 5 \
    --json status,conclusion,createdAt \
    --jq '[.[] | select(.createdAt > "'"$(date -u -v-1H +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u --date='1 hour ago' +%Y-%m-%dT%H:%M:%SZ)"'")]' \
    2>/dev/null || echo "[]")

  if echo "$WORKFLOW_STATUS" | jq -e 'length > 0' > /dev/null 2>&1; then
    FAILED=$(echo "$WORKFLOW_STATUS" | jq '[.[] | select(.conclusion == "failure")] | length')
    if [ "$FAILED" -gt 0 ]; then
      fail "issue-ops workflow had ${FAILED} failed run(s) in the last hour"
      PASS=false
      REPORT="${REPORT}\nFAIL: ${FAILED} workflow run(s) failed"
    else
      ok "All recent issue-ops runs completed without failure"
    fi
  else
    warn "Could not retrieve workflow run status"
  fi
fi

# ── Cleanup ───────────────────────────────────────────────────────────────────

if [ -n "$ISSUE_NUMBER" ] && [ "$DRY_RUN" != "true" ]; then
  log "Closing E2E test issue #${ISSUE_NUMBER}..."
  gh issue close "${ISSUE_NUMBER}" \
    --repo "${REPO}" \
    --comment "E2E test complete. Result: $([ "$PASS" = "true" ] && echo 'PASS ✓' || echo 'FAIL ✗')" \
    2>/dev/null || warn "Could not close issue #${ISSUE_NUMBER}"

  gh issue lock "${ISSUE_NUMBER}" \
    --repo "${REPO}" \
    --reason "resolved" \
    2>/dev/null || true
fi

# ── Final report ──────────────────────────────────────────────────────────────

echo ""
echo "════════════════════════════════════════"
echo "  OpenCI E2E Test Report"
echo "════════════════════════════════════════"
echo -e "$REPORT"
echo ""

if [ "$PASS" = "true" ]; then
  ok "E2E PASS — agentic issue workflow responded correctly"
  exit 0
else
  fail "E2E FAIL — see report above"
  exit 1
fi
