name: test-with-empty-perm
on:
  workflow_call:
permissions: {}
concurrency:
  group: test-${{ github.run_id }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "empty permissions works"
